using JobFinder.Data.Models;
using JobFinder.Data.Models.Nomenclature;
using Microsoft.EntityFrameworkCore;

namespace JobFinder.Data.Seeders
{
    public class CitizenshipsSeeder
    {
        public static void Seed(ModelBuilder builder)
        {
            builder.Entity<CitizenshipEntity>().HasData(
                new CitizenshipEntity { Name = "Afghanistan", Id = 1 },
                new CitizenshipEntity { Name = "Albanian", Id = 2 },
                new CitizenshipEntity { Name = "Algeria", Id = 3 },
                new CitizenshipEntity { Name = "American", Id = 4 },
                new CitizenshipEntity { Name = "Andorra", Id = 5 },
                new CitizenshipEntity { Name = "Angola", Id = 6 },
                new CitizenshipEntity { Name = "Anguilla", Id = 7 },
                new CitizenshipEntity { Name = "Antarctica", Id = 8 },
                new CitizenshipEntity { Name = "Antigua and Barbuda", Id = 9 },
                new CitizenshipEntity { Name = "Argentina", Id = 10 },
                new CitizenshipEntity { Name = "Armenia", Id = 11 },
                new CitizenshipEntity { Name = "Aruba", Id = 12 },
                new CitizenshipEntity { Name = "Australia", Id = 13 },
                new CitizenshipEntity { Name = "Austrian", Id = 14 },
                new CitizenshipEntity { Name = "Azerbaijan", Id = 15 },
                new CitizenshipEntity { Name = "Bahamas", Id = 16 },
                new CitizenshipEntity { Name = "Bahrain", Id = 17 },
                new CitizenshipEntity { Name = "Bangladesh", Id = 18 },
                new CitizenshipEntity { Name = "Barbados", Id = 19 },
                new CitizenshipEntity { Name = "Belarus", Id = 20 },
                new CitizenshipEntity { Name = "Belgium", Id = 21 },
                new CitizenshipEntity { Name = "Belize", Id = 22 },
                new CitizenshipEntity { Name = "Benin", Id = 23 },
                new CitizenshipEntity { Name = "Bermuda", Id = 24 },
                new CitizenshipEntity { Name = "Bhutan", Id = 25 },
                new CitizenshipEntity { Name = "Bolivia", Id = 26 },
                new CitizenshipEntity { Name = "BosniaAndHerzegovina", Id = 27 },
                new CitizenshipEntity { Name = "Botswana", Id = 28 },
                new CitizenshipEntity { Name = "BouvetIsland", Id = 29 },
                new CitizenshipEntity { Name = "Brazil", Id = 30 },
                new CitizenshipEntity { Name = "BritishIndianOceanTerritory", Id = 31 },
                new CitizenshipEntity { Name = "BruneiDarussalam", Id = 32 },
                new CitizenshipEntity { Name = "Bulgarian", Id = 33 },
                new CitizenshipEntity { Name = "BurkinaFaso", Id = 34 },
                new CitizenshipEntity { Name = "Burundi", Id = 35 },
                new CitizenshipEntity { Name = "Cambodia", Id = 36 },
                new CitizenshipEntity { Name = "Cameroon", Id = 37 },
                new CitizenshipEntity { Name = "Canada", Id = 38 },
                new CitizenshipEntity { Name = "CapeVerde", Id = 39 },
                new CitizenshipEntity { Name = "CaymanIslands", Id = 40 },
                new CitizenshipEntity { Name = "CentralAfricanRepublic", Id = 41 },
                new CitizenshipEntity { Name = "Chad", Id = 42 },
                new CitizenshipEntity { Name = "Chile", Id = 43 },
                new CitizenshipEntity { Name = "China", Id = 44 },
                new CitizenshipEntity { Name = "ChristmasIsland", Id = 45 },
                new CitizenshipEntity { Name = "CocosIslands", Id = 46 },
                new CitizenshipEntity { Name = "Colombia", Id = 47 },
                new CitizenshipEntity { Name = "Comoros", Id = 48 },
                new CitizenshipEntity { Name = "Congo", Id = 49 },
                new CitizenshipEntity { Name = "CongoTheDemocraticRepublic", Id = 50 },
                new CitizenshipEntity { Name = "CookIslands", Id = 51 },
                new CitizenshipEntity { Name = "CostaRica", Id = 52 },
                new CitizenshipEntity { Name = "CoteDIvoire", Id = 53 },
                new CitizenshipEntity { Name = "Croatia", Id = 54 },
                new CitizenshipEntity { Name = "Cuba", Id = 55 },
                new CitizenshipEntity { Name = "Cyprus", Id = 56 },
                new CitizenshipEntity { Name = "CzechRepublic", Id = 57 },
                new CitizenshipEntity { Name = "Denmark", Id = 58 },
                new CitizenshipEntity { Name = "Djibouti", Id = 59 },
                new CitizenshipEntity { Name = "Dominica", Id = 60 },
                new CitizenshipEntity { Name = "DominicanRepublic", Id = 61 },
                new CitizenshipEntity { Name = "Ecuador", Id = 62 },
                new CitizenshipEntity { Name = "Egypt", Id = 63 },
                new CitizenshipEntity { Name = "ElSalvador", Id = 64 },
                new CitizenshipEntity { Name = "EquatorialGuinea", Id = 65 },
                new CitizenshipEntity { Name = "Eritrea", Id = 66 },
                new CitizenshipEntity { Name = "Estonia", Id = 67 },
                new CitizenshipEntity { Name = "Ethiopia", Id = 68 },
                new CitizenshipEntity { Name = "FalklandIslands", Id = 69 },
                new CitizenshipEntity { Name = "FaroeIslands", Id = 70 },
                new CitizenshipEntity { Name = "Fiji", Id = 71 },
                new CitizenshipEntity { Name = "Finland", Id = 72 },
                new CitizenshipEntity { Name = "France", Id = 73 },
                new CitizenshipEntity { Name = "FrenchGuiana", Id = 74 },
                new CitizenshipEntity { Name = "FrenchPolynesia", Id = 75 },
                new CitizenshipEntity { Name = "FrenchSouthernTerritories", Id = 76 },
                new CitizenshipEntity { Name = "Gabon", Id = 77 },
                new CitizenshipEntity { Name = "Gambia", Id = 78 },
                new CitizenshipEntity { Name = "Georgia", Id = 79 },
                new CitizenshipEntity { Name = "Germany", Id = 80 },
                new CitizenshipEntity { Name = "Ghana", Id = 81 },
                new CitizenshipEntity { Name = "Gibraltar", Id = 82 },
                new CitizenshipEntity { Name = "Greece", Id = 83 },
                new CitizenshipEntity { Name = "Greenland", Id = 84 },
                new CitizenshipEntity { Name = "Grenada", Id = 85 },
                new CitizenshipEntity { Name = "Guadeloupe", Id = 86 },
                new CitizenshipEntity { Name = "Guam", Id = 87 },
                new CitizenshipEntity { Name = "Guatemala", Id = 88 },
                new CitizenshipEntity { Name = "Guernsey", Id = 89 },
                new CitizenshipEntity { Name = "Guinea", Id = 90 },
                new CitizenshipEntity { Name = "GuineaBissau", Id = 91 },
                new CitizenshipEntity { Name = "Guyana", Id = 92 },
                new CitizenshipEntity { Name = "Haiti", Id = 93 },
                new CitizenshipEntity { Name = "HeardIslandAndMcdonaldIslands", Id = 94 },
                new CitizenshipEntity { Name = "HolySeeVaticanCityState", Id = 95 },
                new CitizenshipEntity { Name = "Honduras", Id = 96 },
                new CitizenshipEntity { Name = "HongKong", Id = 97 },
                new CitizenshipEntity { Name = "Hungary", Id = 98 },
                new CitizenshipEntity { Name = "Iceland", Id = 99 },
                new CitizenshipEntity { Name = "India", Id = 100 },
                new CitizenshipEntity { Name = "Indonesia", Id = 101 },
                new CitizenshipEntity { Name = "Iran", Id = 102 },
                new CitizenshipEntity { Name = "Iraq", Id = 103 },
                new CitizenshipEntity { Name = "Ireland", Id = 104 },
                new CitizenshipEntity { Name = "IsleOfMan", Id = 105 },
                new CitizenshipEntity { Name = "Israel", Id = 106 },
                new CitizenshipEntity { Name = "Italy", Id = 107 },
                new CitizenshipEntity { Name = "Jamaica", Id = 108 },
                new CitizenshipEntity { Name = "Japan", Id = 109 },
                new CitizenshipEntity { Name = "Jersey", Id = 110 },
                new CitizenshipEntity { Name = "Jordan", Id = 111 },
                new CitizenshipEntity { Name = "Kazakhstan", Id = 112 },
                new CitizenshipEntity { Name = "Kenya", Id = 113 },
                new CitizenshipEntity { Name = "Kiribati", Id = 114 },
                new CitizenshipEntity { Name = "KoreaDemocraticPeople", Id = 115 },
                new CitizenshipEntity { Name = "Korea", Id = 116 },
                new CitizenshipEntity { Name = "Kuwait", Id = 117 },
                new CitizenshipEntity { Name = "Kyrgyzstan", Id = 118 },
                new CitizenshipEntity { Name = "LandIslands", Id = 119 },
                new CitizenshipEntity { Name = "LaoPeople", Id = 120 },
                new CitizenshipEntity { Name = "Latvia", Id = 121 },
                new CitizenshipEntity { Name = "Lebanon", Id = 122 },
                new CitizenshipEntity { Name = "Lesotho", Id = 123 },
                new CitizenshipEntity { Name = "Liberia", Id = 124 },
                new CitizenshipEntity { Name = "LibyanArabJamahiriya", Id = 125 },
                new CitizenshipEntity { Name = "Liechtenstein", Id = 126 },
                new CitizenshipEntity { Name = "Lithuania", Id = 127 },
                new CitizenshipEntity { Name = "Luxembourg", Id = 128 },
                new CitizenshipEntity { Name = "Macao", Id = 129 },
                new CitizenshipEntity { Name = "Macedonia", Id = 130 },
                new CitizenshipEntity { Name = "Madagascar", Id = 131 },
                new CitizenshipEntity { Name = "Malawi", Id = 132 },
                new CitizenshipEntity { Name = "Malaysia", Id = 133 },
                new CitizenshipEntity { Name = "Maldives", Id = 134 },
                new CitizenshipEntity { Name = "Mali", Id = 135 },
                new CitizenshipEntity { Name = "Malta", Id = 136 },
                new CitizenshipEntity { Name = "MarshallIslands", Id = 137 },
                new CitizenshipEntity { Name = "Martinique", Id = 138 },
                new CitizenshipEntity { Name = "Mauritania", Id = 139 },
                new CitizenshipEntity { Name = "Mauritius", Id = 140 },
                new CitizenshipEntity { Name = "Mayotte", Id = 141 },
                new CitizenshipEntity { Name = "Mexico", Id = 142 },
                new CitizenshipEntity { Name = "Micronesia", Id = 143 },
                new CitizenshipEntity { Name = "Moldova", Id = 144 },
                new CitizenshipEntity { Name = "Monaco", Id = 145 },
                new CitizenshipEntity { Name = "Mongolia", Id = 146 },
                new CitizenshipEntity { Name = "Montenegro", Id = 147 },
                new CitizenshipEntity { Name = "Montserrat", Id = 148 },
                new CitizenshipEntity { Name = "Morocco", Id = 149 },
                new CitizenshipEntity { Name = "Mozambique", Id = 150 },
                new CitizenshipEntity { Name = "Myanmar", Id = 151 },
                new CitizenshipEntity { Name = "Namibia", Id = 152 },
                new CitizenshipEntity { Name = "Nauru", Id = 153 },
                new CitizenshipEntity { Name = "Nepal", Id = 154 },
                new CitizenshipEntity { Name = "Netherlands", Id = 155 },
                new CitizenshipEntity { Name = "NetherlandsAntilles", Id = 156 },
                new CitizenshipEntity { Name = "NewCaledonia", Id = 157 },
                new CitizenshipEntity { Name = "NewZealand", Id = 158 },
                new CitizenshipEntity { Name = "Nicaragua", Id = 159 },
                new CitizenshipEntity { Name = "Niger", Id = 160 },
                new CitizenshipEntity { Name = "Nigeria", Id = 161 },
                new CitizenshipEntity { Name = "Niue", Id = 162 },
                new CitizenshipEntity { Name = "NorfolkIsland", Id = 163 },
                new CitizenshipEntity { Name = "NorthernMarianaIslands", Id = 164 },
                new CitizenshipEntity { Name = "Norway", Id = 165 },
                new CitizenshipEntity { Name = "Oman", Id = 166 },
                new CitizenshipEntity { Name = "Pakistan", Id = 167 },
                new CitizenshipEntity { Name = "Palau", Id = 168 },
                new CitizenshipEntity { Name = "PalestinianTerritory", Id = 169 },
                new CitizenshipEntity { Name = "Panama", Id = 170 },
                new CitizenshipEntity { Name = "PapuaNewGuinea", Id = 171 },
                new CitizenshipEntity { Name = "Paraguay", Id = 172 },
                new CitizenshipEntity { Name = "Peru", Id = 173 },
                new CitizenshipEntity { Name = "Philippines", Id = 174 },
                new CitizenshipEntity { Name = "Pitcairn", Id = 175 },
                new CitizenshipEntity { Name = "Poland", Id = 176 },
                new CitizenshipEntity { Name = "Portugal", Id = 177 },
                new CitizenshipEntity { Name = "PuertoRico", Id = 178 },
                new CitizenshipEntity { Name = "Qatar", Id = 179 },
                new CitizenshipEntity { Name = "Reunion", Id = 180 },
                new CitizenshipEntity { Name = "Romania", Id = 181 },
                new CitizenshipEntity { Name = "RussianFederation", Id = 182 },
                new CitizenshipEntity { Name = "RWANDA", Id = 183 },
                new CitizenshipEntity { Name = "SaintHelena", Id = 184 },
                new CitizenshipEntity { Name = "SaintKittsAndNevis", Id = 185 },
                new CitizenshipEntity { Name = "SaintLucia", Id = 186 },
                new CitizenshipEntity { Name = "Saint Pierre And Miquelon", Id = 187 },
                new CitizenshipEntity { Name = "Saint Vincent And The Grenadines", Id = 188 },
                new CitizenshipEntity { Name = "Samoa", Id = 189 },
                new CitizenshipEntity { Name = "San Marino", Id = 190 },
                new CitizenshipEntity { Name = "Sao Tome And Principe", Id = 191 },
                new CitizenshipEntity { Name = "Saudi Arabia", Id = 192 },
                new CitizenshipEntity { Name = "Senegal", Id = 193 },
                new CitizenshipEntity { Name = "Serbia", Id = 194 },
                new CitizenshipEntity { Name = "Seychelles", Id = 195 },
                new CitizenshipEntity { Name = "SierraLeone", Id = 196 },
                new CitizenshipEntity { Name = "Singapore", Id = 197 },
                new CitizenshipEntity { Name = "Slovakia", Id = 198 },
                new CitizenshipEntity { Name = "Slovenia", Id = 199 },
                new CitizenshipEntity { Name = "SolomonIslands", Id = 200 },
                new CitizenshipEntity { Name = "Somalia", Id = 201 },
                new CitizenshipEntity { Name = "SouthAfrica", Id = 202 },
                new CitizenshipEntity { Name = "South Georgia And The South Sandwich Islands", Id = 203 },
                new CitizenshipEntity { Name = "Spain", Id = 204 },
                new CitizenshipEntity { Name = "SriLanka", Id = 205 },
                new CitizenshipEntity { Name = "Sudan", Id = 206 },
                new CitizenshipEntity { Name = "Suriname", Id = 207 },
                new CitizenshipEntity { Name = "SvalbardAndJanMayen", Id = 208 },
                new CitizenshipEntity { Name = "Swaziland", Id = 209 },
                new CitizenshipEntity { Name = "Sweden", Id = 210 },
                new CitizenshipEntity { Name = "Switzerland", Id = 211 },
                new CitizenshipEntity { Name = "SyrianArabRepublic", Id = 212 },
                new CitizenshipEntity { Name = "TaiwanProvinceOfChina", Id = 213 },
                new CitizenshipEntity { Name = "Tajikistan", Id = 214 },
                new CitizenshipEntity { Name = "Tanzania", Id = 215 },
                new CitizenshipEntity { Name = "Thailand", Id = 216 },
                new CitizenshipEntity { Name = "TimorLeste", Id = 217 },
                new CitizenshipEntity { Name = "Togo", Id = 218 },
                new CitizenshipEntity { Name = "Tokelau", Id = 219 },
                new CitizenshipEntity { Name = "Tonga", Id = 220 },
                new CitizenshipEntity { Name = "TrinidadAndTobago", Id = 221 },
                new CitizenshipEntity { Name = "Tunisia", Id = 222 },
                new CitizenshipEntity { Name = "Turkey", Id = 223 },
                new CitizenshipEntity { Name = "Turkmenistan", Id = 224 },
                new CitizenshipEntity { Name = "TurksAndCaicosIslands", Id = 225 },
                new CitizenshipEntity { Name = "Tuvalu", Id = 226 },
                new CitizenshipEntity { Name = "Uganda", Id = 227 },
                new CitizenshipEntity { Name = "Ukraine", Id = 228 },
                new CitizenshipEntity { Name = "UnitedArabEmirates", Id = 229 },
                new CitizenshipEntity { Name = "United Kingdom", Id = 230 },
                new CitizenshipEntity { Name = "United States", Id = 231 },
                new CitizenshipEntity { Name = "United States Minor Outlying Islands", Id = 232 },
                new CitizenshipEntity { Name = "Uruguay", Id = 233 },
                new CitizenshipEntity { Name = "Uzbekistan", Id = 234 },
                new CitizenshipEntity { Name = "Vanuatu", Id = 235 },
                new CitizenshipEntity { Name = "Venezuela", Id = 236 },
                new CitizenshipEntity { Name = "Vietnam", Id = 237 },
                new CitizenshipEntity { Name = "VirginIslandsBritish", Id = 238 },
                new CitizenshipEntity { Name = "VirginIslandsUS", Id = 239 },
                new CitizenshipEntity { Name = "Wallis And Futuna", Id = 240 },
                new CitizenshipEntity { Name = "Western Sahara", Id = 241 },
                new CitizenshipEntity { Name = "Yemen", Id = 242 },
                new CitizenshipEntity { Name = "Zambia", Id = 243 },
                new CitizenshipEntity { Name = "Zimbabwe", Id = 244 });
        }
    }
}
