namespace JobFinder.Data.Models.Enums
{
    public enum BusinessSector
    {
        Accounting = 0,
        Advertising = 1,
        Agriculture = 2,
        ArchitectureAndConstruction = 3,
        ArtsAndEntertainment = 4,
        Automotive = 5,
        Aviation = 6,
        BanksAndCredit = 7,        
        ChemicalAndMining = 8,
        ConsultancyServices = 9,
        Education = 10,
        Electronics = 11,
        Electrical = 12,
        EnergyAndUtilities = 13,
        FoodAndBeverage = 14,
        Healthcare = 15,
        HumanResources = 16,
        InformationTechnologies = 17,
        Insurance = 18,
        Internet = 19,
        Legal = 20,
        Manufacturing = 21,
        Machinery = 22,
        Marketing = 23,
        Media = 24,
        NGOs = 25,
        Pharmaceutical = 26,
        PublicAdministration = 27,
        RealEstate = 27,
        Science = 28,
        Security = 29,
        Services = 30,
        SportsAndRecreation = 31,
        Telecommunications = 32,
        TextileIndustry = 33,
        TourismAndRestaurants = 34,
        Trade = 35,
        TransportationAndLogistics = 36,
        Other = 37,
    }
}
